 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note?useSSL=false
    
    username: root
    password: SHRA1raj@2050
   
  jpa:
    hibernate:
      ddl-auto: update
       
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  